name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Autograding
        uses: education/autograding@v1
      - name: Upload Jest output
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jest-report
          path: ./.github/.test/results.json
          if-no-files-found: error
